@startuml
skinparam shadowing false
skinparam rectangle {
  roundCorner 10
}
skinparam defaultFontSize 12

left to right direction

rectangle "**Bundle: eNotfallpass Document**" as Bundle #orange/yellow {

  together {
    rectangle "**Entry: Composition**" as Comp #cornflowerblue/lightblue {
      rectangle "Patient (Reference)  " as PatRef #yellowgreen
      rectangle "Emergency Contacts" as SecContact #yellowgreen
      rectangle "Care Team              " as SecCare #yellowgreen
      rectangle "Resuscitation           " as SecRes #yellowgreen
      rectangle "Medication              " as SecMed #yellowgreen
      rectangle "Immunizations         " as SecImm #yellowgreen
      rectangle "Allergies                  " as SecAllergy #yellowgreen
      rectangle "Risk Factors             " as SecRisk #yellowgreen
      rectangle "Problem list              " as SecDiag #yellowgreen
      rectangle "Advance Directives  " as SecAD #yellowgreen
      rectangle "Other Documents     " as SecOther #yellowgreen
      rectangle "Implants                   " as SecImpl #yellowgreen
      rectangle "Pregnancy               " as SecPreg #yellowgreen
      rectangle "Cognitive disabilities" as SecCogDis #yellowgreen
      rectangle "Physical disabilities  " as SecPhyDis #yellowgreen
    }
  }

  together {
    rectangle "[[StructureDefinition-ch-emr-patient.html Entry: Patient]]" as E1 #salmon
    rectangle "[[StructureDefinition-ch-emr-relatedperson.html Entry: RelatedPerson]]" as E2 #salmon
    rectangle "[[StructureDefinition-ch-emr-practitioner.html Entry: Practitioner]]" as E3 #salmon
    rectangle "[[StructureDefinition-ch-emr-observation-resuscitation-status.html Entry: Observation]]" as E4 #salmon
    rectangle "[[StructureDefinition-ch-emr-observation-cognitive-disability.html Entry: MedicationStatement]]" as E5 #salmon
    rectangle "[[StructureDefinition-ch-emr-observation-physical-disability.html Entry: Immunization]]" as E6 #salmon
    rectangle "[[StructureDefinition-ch-emr-condition-riskFactors.html Entry: AllergyIntolerance]]" as E7 #salmon
    rectangle "[[StructureDefinition-ch-emr-medicationstatement.html Entry: Condition (RiskFactors)]]" as E8 #salmon
    rectangle "[[StructureDefinition-ch-emr-allergyintolerance.html Entry: Condition (ProblemList)]]" as E9 #salmon
    rectangle "[[StructureDefinition-ch-emr-documentreference-advance-directive.html Entry: DocumentReference (AdvanceDirective)]]" as E10 #salmon
    rectangle "[[StructureDefinition-ch-emr-documentreference.html Entry: DocumentReference (Other)]]" as E11 #salmon
    rectangle "[[StructureDefinition-ch-emr-device.html Entry: Device]]" as E12 #salmon
    rectangle "[[StructureDefinition-ch-emr-observation-pregnancy-status.html Entry: Observation (PregnancyStatus)]]" as E13 #salmon
    rectangle "[[StructureDefinition-ch-emr-observation-cognitive-disability.html Entry: Observation (Cog)]]" as E14 #salmon
    rectangle "[[StructureDefinition-ch-emr-observation-physical-disability.html Entry: Observation (Phys)]]" as E15 #salmon
  }
}

PatRef ..> E1
SecContact ..> E2
SecCare ..> E3
SecRes ..> E4
SecMed ..> E5
SecImm ..> E6
SecAllergy ..> E7
SecRisk ..> E8
SecDiag ..> E9
SecAD ..> E10
SecOther ..> E11
SecImpl ..> E12
SecPreg ..> E13
SecCogDis ..> E14
SecPhyDis ..> E15

@enduml
